#!/bin/bash
#
# This shouldn't be used as a script for now
#
# Current docker instructions for Debian 16.04 LTS
#
exit 1

sudo apt-get install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install docker-engine
sudo systemctl enable docker
sudo systemctl start docker

sudo usermod -aG docker $(whoami)

