#!/bin/bash
verbose=false

#Include functions
source scripts/functions

while getopts ":hv" OPTION; do
    case $OPTION in
        h) usage; exit 0 ;;
        v) verbose=true ;;
    esac
done
shift $(( OPTIND - 1 ))

# OS detection
UNAME=$(uname -a | sed -E 's/ .*//')
if [[ $UNAME == 'Darwin' ]]; then
    run echo "Machine type is Mac..."
    source scripts/mac
    if [[ $? -ne 0 ]]; then
        echo "Error while executing Mac installer, aborting..."
        exit 1
    fi
    ZSH_PATH="/usr/local/bin/zsh"
    # Fix for font cache reset failure due to fontconfig error
    FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig
elif [[ $UNAME == 'Linux' ]]; then
    run echo "Machine type is Linux..."
    source scripts/linux
    if [[ $? -ne 0 ]]; then
        echo "Error while executing Linux installer, aborting..."
        exit 1
    fi
    ZSH_PATH="/bin/zsh"
else
    echo "Could not detect Operating System. Aborting."
    exit 1
fi

# Start OS agnostic configuration
run echo "Executing OS agnostic configuration"
source scripts/agnostic

# Change shell to zsh
if [[ $SHELL != $ZSH_PATH ]]; then
    if [[ ! -e $ZSH_PATH ]]; then
        echo "Couldn't find zsh at $ZSH_PATH, please install..."
    else
        run grep $ZSH_PATH /etc/shells
        if [[ $? -ne 0 ]]
        then
            run echo "Adding $ZSH_PATH to /etc/shells, password may be requested..."
            echo $ZSH_PATH | sudo tee -a /etc/shells
        fi
        run echo "Changing shell to zsh..."
        if [[ $UID == 0 ]]; then
            USER="root"
        fi
        run sudo chsh -s "$ZSH_PATH" "$USER"
    fi
else
    run echo "Shell already set up to zsh"
fi

# Update .zshrc according to environment
# TODO: Need to rearrange this function's location
if [[ $UNAME == 'Darwin' ]]; then
    sed -i -e "s/^plugins=.*/plugins=\(aws brew docker docker-compose gitfast knife osx pip sudo\)/g" ~/.zshrc
elif [[ -e /etc/arch-release ]]; then
    sed -i -e "s/^plugins=.*/plugins=\(archlinux docker docker-compose gitfast pip sudo\)/g" ~/.zshrc
else
    sed -i -e "s/^plugins=.*/plugins=\(gitfast pip sudo\)/g" ~/.zshrc
fi

