#!/bin/bash

# Update installer submodules
run echo "Updating installer submodules..."
git submodule update --init --recursive --remote

# Check if pip needs to be installed / upgraded
run echo "Checking if pip needs to be installed or upgraded, password may be requested..."
run sudo pip install --upgrade pip
if [[ $? -ne 0 ]]; then
    echo "Error while executing Mac installer, aborting..."
    exit 1
fi

# Install required python packages
pip_packages=( fabric setuptool termcolor virtualenvwrapper )
run echo "Checking required pip packages..."
for i in "${pip_packages[@]}"; do
    run pip list | grep -i $i
    if [[ $? -ne 0 ]]
    then
        run echo "Installing pip package $i, password may be requested..."
        run sudo pip install $i
    fi
done

# Install Powerline fonts
run echo "Installing powerline fonts..."
run powerline-fonts/install.sh

# Syncronise profile files
run echo "Synchronising profile dotfiles..."
run rsync -r generic/ ~/
if [[ -e ~/Google\ Drive/Scripts/.zshrc_aliases ]]
then
    run cp ~/Google\ Drive/Scripts/.zshrc_aliases ~/
else
    echo "Couldn't find .zshrc_aliases, please add manually."
fi

# Configure VIm
run echo "Installing/updating vimplug... "
if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
    mkdir -p ~/.vim/autoload
    run curl -sSfLo ~/.vim/autoload/plug.vim \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
run vim -esu ~/.vimrc +PlugUpgrade +qa || true
run vim -esu ~/.vimrc +PlugClean! +qa || true
run vim -esu ~/.vimrc +PlugUpdate +qa || true

# Install or update oh-my-zsh
if [[ ! -d ~/.oh-my-zsh ]]; then
    run echo "Installing oh-my-zsh..."
    run git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
else 
    run echo "Oh-my-zsh already installed, updating..."
    run git -C ~/.oh-my-zsh reset --hard origin/master
    run git -C ~/.oh-my-zsh pull
fi

# Install or update fzf 
if [[ ! -d ~/.fzf ]]; then
    run echo "Installing fzf..."
    run git clone https://github.com/junegunn/fzf.git ~/.fzf
    run ~/.fzf/install --all
else
    run echo "fzf already installed, updating..."
    run git -C ~/.fzf reset --hard origin/master
    run git -C ~/.fzf pull
fi
