#!/bin/bash

function usage {
    echo "Enabled options are '-h' for this message and '-v' for for verbose mode"
}

function run () {
    if $verbose
    then
        if [[ `echo $@ | cut -c1-4` != "echo" ]]
        then
            echo "> Executing $@..."
        fi
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}
