#!/bin/bash

function run () {
    if $verbose
    then
        if [[ `echo $@ | cut -c1-4` != "echo" ]]
        then
            echo "> Executing $@..."
        fi
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}
