#!/bin/bash
# TODO: This script currently only works in Arch Linux, need to generalise it

# Include functions
source scripts/functions

# Install required packages
PACMAN_PKG="fzf gcc python-pip rsync sudo vim zsh"
if [[ $UID == 0 ]]; then
    run pacman -S --noconfirm --needed $PACMAN_PKG
else
    run sudo pacman -S --noconfirm --needed $PACMAN_PKG
fi
