#!/bin/bash
# Linux script is currently detecting Centos/RHEL, Arch and Debian/Ubuntu

# Check if elevation is required
if [[ $UID != 0 ]]; then
    ELEVATE="sudo "
else
    ELEVATE=""
fi

if [[ -e /etc/redhat-release ]]; then
    DISTRO="redhat"
    PACKAGES="gcc python-devel python-pip rsync sudo vim zsh"
    RUN_COMMAND="yum install -y "
elif [[ -e /etc/arch-release ]]; then
    DISTRO="arch"
    PACKAGES="fzf gcc python-pip rsync sudo vim zsh"
    RUN_COMMAND="pacman -S --noconfirm --needed "
elif [[ -e /etc/debian_version ]]; then
    DISTRO="debian"
    PACKAGES="gcc python-dev python-pip rsync vim zsh"
    run $ELEVATE apt-get update
    RUN_COMMAND="apt-get install -y "
else
    echo "ERROR: Could not determine Linux distribution, exiting..."
    exit 1
fi

# Install required packages
run $ELEVATE $RUN_COMMAND $PACKAGES
