#!/bin/bash
# TODO: Add more distros. Currently only executes on Arch or Centos/RHEL

# Include functions
source scripts/functions

if [[ -e /etc/redhat-release ]]; then
    DISTRO="redhat"
    PACKAGES="gcc python-dev python-pip rsync sudo vim zsh"
    RUN_COMMAND="yum install -y "
elif [[ -e /etc/arch-release ]]; then
    DISTRO="arch"
    PACKAGES="fzf gcc python-pip rsync sudo vim zsh"
    RUN_COMMAND="pacman -S --noconfirm --needed "
else
    echo "ERROR: Could not determine Linux distribution, exiting..."
    exit 1
fi

# Check if elevation is required
if [[ $UID != 0 ]]; then
    ELEVATE="sudo "
else
    ELEVATE=""
fi

# Install required packages
run $ELEVATE $RUN_COMMAND $PACKAGES
