#!/bin/bash

# Check if Xcode is installed
# (Maybe replace with check 'xcode-select -p', which should return 0 if installed, 2 if missing)
if [[ ! -e /usr/bin/gcc ]]
then
    echo "Xcode isn't installed, please install from the App Store"
    exit 1
fi

# Check if homebrew is already installed
if [[ ! -e /usr/local/bin/brew ]]
then
    run echo "Installing homebrew..."
    run ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    run echo "Homebrew has already been installed"
fi

# Install homebrew bottles
brew_bottles=( aria2 awscli cmake ctags dos2unix git gnupg jq libxml2 maven ncdu nmap openssl pv python3 rbenv syncthing unrar vim wakeonlan watch wget zsh zsh-completions )
for i in "${brew_bottles[@]}"
do
    if [[ ! -e "/usr/local/Cellar/$i" ]]
    then
        run echo "Installing $i homebrew bottle..."
        run brew install $i
    fi
done

# Install homebrew meld
if [[ ! -e "/usr/local/Caskroom/meld" ]]
then
    run echo "Installing meld..."
    run brew cask install meld
else
    run echo "Meld has already been installed"
fi

# Checking if applications are installed
if [[ ! -d /Applications/iTerm.app ]]
then
    echo "Couldn't find iTerm 2, please install."
fi
